FROM python:3.10-slim

# Instala dependencias
RUN pip install --upgrade pip
COPY requirements_mlflow.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

# Define directorio de trabajo
WORKDIR /app