FROM python:3.10-slim

# Instala dependencias del sistema
RUN apt-get update && apt-get install -y \
    openjdk-17-jre-headless \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_torchserve.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

# Define JAVA_HOME para Java 17
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Directorio de trabajo
WORKDIR /home/model-server

