FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_torchserve.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

WORKDIR /app

CMD ["/app/model_store/create_mar.sh"]