FROM python:3.12-slim

# Instala dependencias del sistema
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-21-jre-headless \
    curl \
    git \
    libxcb1 \
    libx11-6 \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_torchserve.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

# Define JAVA_HOME para Java 21
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"


# Directorio de trabajo
WORKDIR /home/model-server

