FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libxcb1 \
    libx11-6 \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    && rm -rf /var/lib/apt/lists/*

# Instala dependencias
RUN pip install --upgrade pip
COPY requirements_trainer.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

# Define directorio de trabajo
WORKDIR /app