inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081

enable_auth=false
enable_metrics_api=false
mlflow_integration_enabled=false
authentication_method=none

model_store=/home/model-server/model-store
