inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://127.0.0.1:8082
model_store=/home/model-server/model-store
load_models=blood_cell_detection=blood_cell_detection.mar
number_of_netty_threads=4
job_queue_size=10
max_response_size=65535000
max_request_size=65535000
disable_token_authorization=true